version: "3.8"

services:
  jupyter:
    image: nvcr.io/nvidia/pytorch:21.07-py3
    ipc: host
    ports:
      - 5500:8888
    working_dir: /app
    command: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --no-browser
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]